#
# Copyright (C) 2021 Kian Cross
#

name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [11, 15, 16]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build 🧰
        run: ./gradlew jar
      
      - name: Package 📦
        run: ./gradlew shadowJar

      - name: Upload Package 📤
        uses: actions/upload-artifact@v3
        if: matrix.java == '11'
        with:
          name: packaged-jar
          path: build/libs/spotbugs-xml-reader-*.jar

      - name: Cleanup Gradle Cache
        shell: bash
        run: |
          ./gradlew --stop
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
 

  test:
    name: Test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    strategy:
      matrix:
        java: [11, 15, 16]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Test 🔬
        run: ./gradlew test
      
      - name: Upload Coverage Report 📤
        uses: codecov/codecov-action@v3.1.1
        env:
          JAVA_VERSION: ${{ matrix.java }}
        with:
          fail_ci_if_error: true
          env_vars: OS,JAVA_VERSION

      - name: Cleanup Gradle Cache
        shell: bash
        run: |
          ./gradlew --stop
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties


  checkstyle:
    name: Checkstyle (${{ matrix.set }})
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        set: [main, test]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - uses: kiancross/checkstyle-annotations-action@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Checkstyle 👠
        run: ./gradlew checkstyle${{ matrix.set }}

      - name: Cleanup Gradle Cache
        shell: bash
        run: |
          ./gradlew --stop
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
